### ISSUE TITLE
[CFP epic] Implement Call for Papers

### ISSUE THREAD

**Issue by alexdeveng** [Spring-io-2024-modulith-workshop/conference-kata-implementation-modulith#1]
# Introduction

Call for papers administration

## Stories to be implemented

- [x] Speaker should be able to send a proposal
- [x] Organizer retrieves all proposals (Gel all proposals)
- [x] Attendee retrieves the list of talks (Get all accepted proposals (talks)) ,depends on #9
- [x] Attendee retrieve more information of a talk (Get by id proposal)

- Create Speaker with information related to the speaker

## Steps
- #4 
- #42
