### ISSUE TITLE
[Attendee epic] Implement attendee system

### ISSUE THREAD

**Issue by alexdeveng** [Spring-io-2024-modulith-workshop/conference-kata-implementation-modulith#10]
# Introduction

System to manage attendee information, such as talks evaluation and access to slides.

## Stories to be implemented

- [ ] Attendee access to slide
- [ ] Attendee checked in at the conference
- [ ] Attendee checked out in the conference

## Stores nice to have

- Attendee when access a Room is validated with a QR code :)
- Manage Room capacity for a specific talk

## Steps

-
