### ISSUE TITLE
[Ticketing Epic] Implement Ticketing Management

### ISSUE THREAD

**Issue by alexdeveng** [Spring-io-2024-modulith-workshop/conference-kata-implementation-modulith#8]
# Introduction

Manages ticket sales and reservations.

## Stories to be implemented

- [x] User can purchase or book a ticket.
- [x] Retrieves the list of tickets
- [x] When a ticket is paid it changes the status of the payment from PENDING to OK. The date of the purchase will be useful if we want to CANCEL the purchase.

## Stores nice to have

- 

## Steps

-

**Comment by alexdeveng** [comment]
I have written down some use stores as an example, feel free to change them. @anyulled

**Comment by alexdeveng** [comment]
Splitting the database maybe could be done in another task ;) up to you
